### ISSUE TITLE
Possible to set this toggled on by default?

### ISSUE THREAD

**Issue by odopo** [yutotakano/mpv_clock#1]
Is it possible to set the clock toggled on by default when mpv runs? I know the _osd-clock.lua_ script can show time as soon as mpv starts but I prefer yours due to the toggle function. I like having clock shown continuously during playback, but I won't be able to read file statistics (shift+i) when needed if _osd-clock.lua_ is configured for continuous display of time. Having a toggle is helpful in such a scenario. So, is it possible to set _mpv_clock.lua_ to display clock at start without pressing the key-bindings?

**Comment by yutotakano** [comment]
Sure! There's no configuration option unfortunately, but it is just adding a new line at the very end containing `osd_clock_toggle()`, so that you call the toggle upon script load (thereby showing the clock indefinitely until you toggle off).

**Comment by odopo** [comment]
Thanks! That works perfectly!
